# SQLite version 3.x
#   gem install sqlite3
#
#   Ensure the SQLite 3 gem is defined in your Gemfile
#   gem 'sqlite3'

defaults: &defaults
  adapter: postgresql
  encoding: unicode
  host: localhost
  pool: 5
  username: sbn_db_user
  password: 4Pong_3Ophir_7Everest*6

# webui:
development:
  <<: *defaults
  database: sbns_ember

test:
  <<: *defaults
  database: sbns_ember_test

production:
  <<: *defaults
  database: sbns_ember_prod
